backend:
  name: git-gateway
  branch: main

# Use custom R2 media backend
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Custom media library for R2
media_library:
  name: r2
  config:
    api_url: /api/cms/media

# Site configuration
site_url: https://jpstas.com
display_url: https://jpstas.com
logo_url: /favicon.svg

# Collections
collections:
  # Portfolio Case Studies
  - name: "portfolio"
    label: "Portfolio Projects"
    label_singular: "Portfolio Project"
    folder: "src/data"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    editor:
      preview: false
    fields:
      - {label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9-]+$', 'Must be lowercase with hyphens'], hint: "URL-friendly identifier (e.g., print-studio)"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tagline", name: "tagline", widget: "text"}
      
      # Hero Section
      - label: "Hero Image"
        name: "hero"
        widget: "object"
        collapsed: false
        fields:
          - {label: "Image URL", name: "src", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
      
      # Metrics
      - label: "Key Metrics"
        name: "metrics"
        widget: "list"
        min: 3
        max: 4
        collapsed: false
        summary: '{{fields.label}}: {{fields.value}}'
        fields:
          - {label: "Label", name: "label", widget: "string"}
          - {label: "Value", name: "value", widget: "string"}
      
      # Meta Information
      - label: "Meta Information"
        name: "meta"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Tags", name: "tags", widget: "list", required: false}
          - {label: "Tools Used", name: "tools", widget: "list", required: false}
          - {label: "Year", name: "year", widget: "string", required: false}
          - {label: "Client", name: "client", widget: "string", required: false}
      
      # Context Section
      - label: "Context & Problem"
        name: "context"
        widget: "object"
        collapsed: false
        fields:
          - {label: "Problem Statement", name: "problem", widget: "text"}
          - label: "Constraints"
            name: "constraints"
            widget: "list"
            required: false
            field: {label: "Constraint", name: "constraint", widget: "string"}
          - {label: "Quote", name: "quote", widget: "text", required: false}
      
      # Solution Section
      - label: "Solution"
        name: "solution"
        widget: "object"
        collapsed: false
        fields:
          - {label: "Approach", name: "approach", widget: "text"}
          - label: "Key Features/Bullets"
            name: "bullets"
            widget: "list"
            required: false
            field: {label: "Feature", name: "bullet", widget: "string"}
          
          # Gallery
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            required: false
            summary: '{{fields.type | upper}}: {{fields.caption}}'
            fields:
              - {label: "Media URL", name: "src", widget: "string", hint: "For images: full URL. For videos: Cloudflare Stream ID (32 char hex)"}
              - {label: "Alt Text", name: "alt", widget: "string", required: false}
              - {label: "Type", name: "type", widget: "select", options: ["image", "video", "gif"], default: "image", required: false}
              - {label: "Poster/Thumbnail", name: "poster", widget: "string", required: false, hint: "For videos only"}
              - {label: "Caption", name: "caption", widget: "string", required: false}
          
          # Before/After Comparison
          - label: "Before & After"
            name: "beforeAfter"
            widget: "object"
            required: false
            collapsed: true
            fields:
              - label: "Before"
                name: "before"
                widget: "object"
                fields:
                  - {label: "Image URL", name: "src", widget: "image"}
                  - {label: "Alt Text", name: "alt", widget: "string"}
              - label: "After"
                name: "after"
                widget: "object"
                fields:
                  - {label: "Image URL", name: "src", widget: "image"}
                  - {label: "Alt Text", name: "alt", widget: "string"}
      
      # Impact Metrics
      - label: "Impact & Results"
        name: "impact"
        widget: "list"
        min: 3
        max: 6
        collapsed: false
        summary: '{{fields.label}}: {{fields.value}}'
        fields:
          - {label: "Label", name: "label", widget: "string"}
          - {label: "Value", name: "value", widget: "string"}
      
      # Process Steps
      - label: "Process/Methodology"
        name: "process"
        widget: "list"
        min: 3
        collapsed: false
        summary: '{{fields.title}}'
        fields:
          - {label: "Step Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Icon", name: "icon", widget: "string", required: false, hint: "Icon identifier (optional)"}
      
      # Reflection
      - label: "Reflection & Learning"
        name: "reflection"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - {label: "Key Learning", name: "learning", widget: "text"}
          - label: "Reusable Patterns"
            name: "reuse"
            widget: "list"
            required: false
            field: {label: "Pattern", name: "pattern", widget: "string"}
      
      # Related Projects
      - label: "Related Projects"
        name: "related"
        widget: "list"
        required: false
        max: 3
        collapsed: true
        summary: '{{fields.title}}'
        fields:
          - {label: "Project Title", name: "title", widget: "string"}
          - {label: "Link", name: "href", widget: "string", hint: "e.g., /portfolio/project-name"}

  # Homepage Content
  - name: "homepage"
    label: "Home Page"
    files:
      - name: "hero"
        label: "Homepage Content"
        file: "src/data/site/homepage.json"
        fields:
          - {label: "Page Title", name: "title", widget: "string", default: "Creative Technologist & Designer"}
          - {label: "Subtitle", name: "subtitle", widget: "string", default: "Transforming business challenges into elegant solutions"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - {label: "Hero Image Alt", name: "heroImageAlt", widget: "string"}
          
          # Featured Projects
          - label: "Featured Projects"
            name: "featuredProjects"
            widget: "list"
            max: 3
            summary: '{{fields.title}}'
            fields:
              - {label: "Project Title", name: "title", widget: "string"}
              - {label: "Slug", name: "slug", widget: "string", hint: "Must match portfolio project slug"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Tags", name: "tags", widget: "list"}
          
          # Stats/Metrics
          - label: "Homepage Metrics"
            name: "metrics"
            widget: "list"
            max: 4
            summary: '{{fields.label}}: {{fields.value}}'
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Value", name: "value", widget: "string"}

  # About Page Content
  - name: "about"
    label: "About Page"
    files:
      - name: "about"
        label: "About Page Content"
        file: "src/data/site/about.json"
        fields:
          - {label: "Heading", name: "heading", widget: "string", default: "About Me"}
          - {label: "Subheading", name: "subheading", widget: "text"}
          - {label: "Bio", name: "bio", widget: "markdown"}
          - {label: "Profile Photo", name: "photo", widget: "image"}
          - {label: "Photo Alt Text", name: "photoAlt", widget: "string"}
          
          # Background
          - label: "Background Section"
            name: "background"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", default: "Background"}
              - label: "Paragraphs"
                name: "paragraphs"
                widget: "list"
                field: {label: "Paragraph", name: "text", widget: "text"}
          
          # Skills
          - label: "Skills"
            name: "skills"
            widget: "list"
            summary: '{{fields.category}}'
            fields:
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Icon Color", name: "iconColor", widget: "string", hint: "CSS color (e.g., primary, secondary)"}
              - label: "Skill List"
                name: "items"
                widget: "list"
                field: {label: "Skill", name: "skill", widget: "string"}
          
          # Experience Timeline
          - label: "Experience"
            name: "experience"
            widget: "list"
            summary: '{{fields.period}}: {{fields.role}}'
            fields:
              - {label: "Period", name: "period", widget: "string", hint: "e.g., 2020 - Present"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Color", name: "color", widget: "select", options: ["primary", "secondary", "highlight"]}
          
          # Call to Action
          - label: "CTA Section"
            name: "cta"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Button Text", name: "buttonText", widget: "string", default: "Get In Touch"}
              - {label: "Button Link", name: "buttonLink", widget: "string", default: "/contact"}

  # Site Settings
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "src/data/site/settings.json"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string", default: "John P. Stas"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - {label: "Author Name", name: "authorName", widget: "string", default: "John P. Stas"}
          - {label: "Author Email", name: "authorEmail", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          
          # Social Links
          - label: "Social Links"
            name: "social"
            widget: "object"
            fields:
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "GitHub", name: "github", widget: "string", required: false}
              - {label: "Email", name: "email", widget: "string"}
          
          # SEO
          - label: "SEO Defaults"
            name: "seo"
            widget: "object"
            fields:
              - {label: "Default Meta Description", name: "description", widget: "text"}
              - {label: "Keywords", name: "keywords", widget: "list"}
              - {label: "OG Image", name: "ogImage", widget: "image", required: false}

