# Wrangler Configuration for CMS Media API Worker
# This is separate from the Pages project

name = "cms-media-api"
main = "cms-media-api.ts"
compatibility_date = "2024-01-01"

# Account ID
account_id = "fa917615d33ac203929027798644acef"

# R2 bucket binding
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "jpstas-media"

# Environment variables
[vars]
CLOUDFLARE_ACCOUNT_ID = "fa917615d33ac203929027798644acef"

# Routes (configure after deployment via dashboard)
# Route: jpstas.com/api/cms/*

